[package]
name = "devnetfaucet"
version = "0.0.0"
edition = "2018"
publish = false
authors = [ "you",]

[lib]
path = "src/faucet.rs"

[dependencies.elrond-wasm]
version = "0.38.0"
features = ["esdt-token-payment-legacy-decode",]

[dev-dependencies.elrond-wasm-debug]
version = "0.38.0"
