[package]
name = "devnetfaucet"
version = "0.0.0"
edition = "2021"
publish = false
authors = [ "you",]

[lib]
path = "src/faucet.rs"

[dependencies.multiversx-sc]
version = "0.52.1"

[dev-dependencies.multiversx-sc-scenario]
version = "0.52.1"
