[package]
name = "devnetfaucet-meta"
version = "0.0.0"
edition = "2021"
publish = false
authors = [ "you",]

[dev-dependencies]

[dependencies.devnetfaucet]
path = ".."

[dependencies.multiversx-sc]
version = "0.52.1"

[dependencies.multiversx-sc-meta]
version = "0.52.1"
