// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            5
// Async Callback (empty):               1
// Total number of exported functions:   8

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    devnetfaucet
    (
        init => init
        upgrade => upgrade
        setClaimsAddress => set_claims_address
        changeClaimsOwnership => change_claims_ownership
        setRewardToken => set_reward_token
        activateFaucet => activate_faucet
        getLastFaucet => last_faucet
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
